FROM node:16.13.0-alpine3.14

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG KEYCLOCK_BASE_URL
ARG KEYCLOCK_CLIENT_ID
ARG KEYCLOCK_ENDPOINT
ARG GOOGLE_ANALYTICS_ID
ENV KEYCLOCK_BASE_URL $KEYCLOCK_BASE_URL
ENV KEYCLOCK_CLIENT_ID $KEYCLOCK_CLIENT_ID
ENV KEYCLOCK_ENDPOINT $KEYCLOCK_ENDPOINT
ENV HOST 0.0.0.0
ENV PORT 3000
ENV GOOGLE_ANALYTICS_ID $GOOGLE_ANALYTICS_ID

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
