export const ENDPOINT_ADUAN = '/aduan/complaints'
export const ENDPOINT_IKP = '/aduan/ikp'
export const ENDPOINT_ADUAN_NON_PEMPROV = '/aduan/non-pemprov-complaints'
export const ENDPOINT_ADUAN_HOTLINE_JABAR = '/aduan/hotline-jabar'
export const ENDPOINT_RW = '/user/rw'
export const ENDPOINT_LURAH = '/user/lurah'
export const ENDPOINT_KEPALA_DESA = '/user/kepala-desa'
