name: Jabar Super Apps Web Admin Production

on:
  push:
    tags:
      - 'v*'

jobs:
  build-push-deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Vault and get secrets
      - name: Get Vault Secrets
        run: |
          # Install Vault CLI
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

          # Set Vault environment variables
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}

          # Get secrets and format them for build-args
          echo "BUILD_ARGS<<EOF" >> $GITHUB_ENV
          vault kv get -format=json kv-superapp-service-production/web-admin | jq -r '.data.data | to_entries[] | "--build-arg \(.key)=\(.value)"' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p '${{ secrets.REGISTRY_PASSWORD }}'

      # Set version dari git tag (hapus prefix 'v')
      - name: Set version tag
        id: vars
        run: |
          # Extract version from git tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      # Build the Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.SERVICE_IMAGENAME }}:${{ env.version }}
            ${{ secrets.SERVICE_IMAGENAME }}:latest
          build-args: |
            ${{ env.BUILD_ARGS }}

      ## GitOps
      - name: GitOps ArgoCD Setup
        run: |
          echo "${{ secrets.GITLAB_ARGOCD_KEY }}" > /tmp/gitlab-deploy-ssh-key
          chmod 600 /tmp/gitlab-deploy-ssh-key
          export GIT_SSH_COMMAND="ssh -i /tmp/gitlab-deploy-ssh-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          git clone ${{ secrets.GITLAB_ARGOCD_REPOSITORY }}

      - name: GitOps ArgoCD Update Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "${{ secrets.SERVICE_IMAGENAME }}:${{ env.version }}"' 'jds-terraform-gke/k8s/superapp/production/web-admin/deployment.yaml'

      - name: GitOps ArgoCD Create Branch, Commit, Push
        id: create_mr
        run: |
          export GIT_SSH_COMMAND="ssh -i /tmp/gitlab-deploy-ssh-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          cd jds-terraform-gke/k8s/superapp/production/web-admin
          git config user.email "github-action@github.com"
          git config user.name "Github Action"

          BRANCH_NAME="release-web-admin-${{ env.version }}"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "[Release] Web Admin v${{ env.version }} to production"
          git push origin $BRANCH_NAME
          
          # Create MR Gitlab
          MR_RESPONSE=$(curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_API_TOKEN }}" \
            --data-urlencode "source_branch=$BRANCH_NAME" \
            --data-urlencode "target_branch=master" \
            --data-urlencode "title=[Release] Superapp Web Admin v${{ env.version }} to production" \
            --data-urlencode "description=# Overview

              - Web Admin Release v${{ env.version }} to production

              ## Evidence

              - title: Release Superapp Web Admin v${{ env.version }} to production
              - project: Sapawarga
              - participants: " \
                          "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/merge_requests")

          MR_URL=$(echo $MR_RESPONSE | jq -r '.web_url')
          echo "mr_url=$MR_URL" >> $GITHUB_OUTPUT

      - uses: appleboy/telegram-action@master
        name: Send release notif to telegram
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            🚀 <b>Superapp Web Admin New Release to Production</b>
            
            Version: <code>v${{ env.version }}</code>
            Released by: <b>${{ github.actor }}</b>
            
            <b>GitHub Release:</b> https://github.com/${{ github.repository }}/releases/tag/v${{ env.version }}
            
            <b>Merge Request:</b> ${{ steps.create_mr.outputs.mr_url }}
            
            ⚠️ Please review and merge the deployment MR @feriahmd
